/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-01 05:55:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateShopForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1705984108000L));
    _jspx_dependants.put("jar:file:/C:/Project/Project/kioskPj/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Project/Project/kioskPj/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Project/Project/kioskPj/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/x.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Project/Project/kioskPj/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/sql.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Project/Project/kioskPj/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- Core -->\r\n");
      out.write("\r\n");
      out.write("<!-- XML -->\r\n");
      out.write("\r\n");
      out.write("<!-- I18N -->\r\n");
      out.write("\r\n");
      out.write("<!-- Database -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	 .content {\r\n");
      out.write("            background-color:rgb(247, 245, 245);\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .innerOuter {\r\n");
      out.write("            border:1px solid lightgray;\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            padding:5% 10%;\r\n");
      out.write("            background-color:white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        table * {margin:5px;}\r\n");
      out.write("        table {width:100%;}\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<br><br>\r\n");
      out.write("		<div class=\"innerOuter\">\r\n");
      out.write("		\r\n");
      out.write("			<h2>'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.shopName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' 정보</h2>\r\n");
      out.write("			<br>\r\n");
      out.write("			<input type=\"hidden\" id=\"shopId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			\r\n");
      out.write("			<form name=\"board\" id=\"board\" method=\"post\" action=\"update.sh\">\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"shopId\">*ID : </label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"shopId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"shopId\" readonly> <br>\r\n");
      out.write("				\r\n");
      out.write("				<label for=\"shopPwd\">*비밀번호 : </label>\r\n");
      out.write("				<input type=\"password\" class=\"form-control\" id=\"shopPwd\" value=\"\" name=\"shopPwd\"> <br>\r\n");
      out.write("				\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<label for=\"shopRepresentative\">*대표자 : </label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"shopRepresentative\" value=\"\" name=\"shopRepresentative\"> <br>\r\n");
      out.write("				\r\n");
      out.write("				<label for=\"shopPhone\">*핸드폰번호 : </label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"shopPhone\" value=\"\" name=\"shopPhone\"> <br>\r\n");
      out.write("				\r\n");
      out.write("				<label for=\"shopEmail\">*이메일 : </label>\r\n");
      out.write("				<input type=\"text\" class=\"form-control\" id=\"shopEmail\" value=\"\" name=\"shopEmail\"> <br>\r\n");
      out.write("				\r\n");
      out.write("				<br>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("				<button type=\"submit\" class=\"bbs-btn-st2 bg-purple3\" onclick=\"formCheck();return false;\" formaction=\"update.sh\">수정</button>\r\n");
      out.write("				<button class=\"bbs-btn-st2 bg-black_r\" onclick=\"history.back();return false;\">취소</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("    function formCheck() {\r\n");
      out.write("        // 필수 필드 가져오기\r\n");
      out.write("        var shopPwd = $(\"#shopPwd\").val();\r\n");
      out.write("        var shopName = $(\"#shopName\").val();\r\n");
      out.write("        var shopRepresentative = $(\"#shopRepresentative\").val();\r\n");
      out.write("        var shopPhone = $(\"#shopPhone\").val();\r\n");
      out.write("        var shopEmail = $(\"#shopEmail\").val();\r\n");
      out.write("\r\n");
      out.write("        // 비밀번호 검사\r\n");
      out.write("        // 조건: 8 ~ 14자, 최소 하나의 특수문자\r\n");
      out.write("        var pwdPattern = /^(?=.*[!@#$%^&*])[A-Za-z\\d!@#$%^&*]{8,14}$/;\r\n");
      out.write("        if (!pwdPattern.test(shopPwd)) {\r\n");
      out.write("            alert(\"비밀번호는 8자 이상 14자 이하로 입력해야하며, 최소 하나의 특수문자가 포함되어야 합니다\");\r\n");
      out.write("            $(\"#shopPwd\").focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 업체명 검사\r\n");
      out.write("        if (shopName === \"\") {\r\n");
      out.write("            alert(\"업체명을 입력하세요.\");\r\n");
      out.write("            $(\"#shopName\").focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 대표자 검사\r\n");
      out.write("        if (shopRepresentative === \"\") {\r\n");
      out.write("            alert(\"대표자 이름을 입력하세요.\");\r\n");
      out.write("            $(\"#shopRepresentative\").focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 핸드폰번호 검사 (기본적인 형식 검사)\r\n");
      out.write("        var phonePattern = /^01[0179][0-9]{7,8}$/; // 간단한 휴대폰 번호 패턴\r\n");
      out.write("        if (!phonePattern.test(shopPhone)) {\r\n");
      out.write("            alert(\"올바른 핸드폰 번호를 입력하세요.\");\r\n");
      out.write("            $(\"#shopPhone\").focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 이메일 검사 (기본적인 이메일 형식 검사)\r\n");
      out.write("        var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$/;\r\n");
      out.write("        if (!emailPattern.test(shopEmail)) {\r\n");
      out.write("            alert(\"올바른 이메일 주소를 입력하세요.\");\r\n");
      out.write("            $(\"#shopEmail\").focus();\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // 모든 검사를 통과하면 AJAX 요청 실행\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'update.sh', \r\n");
      out.write("            type: 'POST', \r\n");
      out.write("            data: $('#board').serialize(), // 폼 데이터 직렬화\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("            	alert('정보가 성공적으로 업데이트되었습니다.');\r\n");
      out.write("                $('#board').submit();\r\n");
      out.write("            },\r\n");
      out.write("            error: function(error) {\r\n");
      out.write("            	alert('업데이트 중 오류가 발생했습니다.');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    	return false;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/updateShopForm.jsp(60,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.shopId ne 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<label for=\"shopName\">*업체명 : </label>\r\n");
          out.write("				<input type=\"text\" class=\"form-control\" id=\"shopName\" value=\"\" name=\"shopName\">\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
